### PR TITLE
Added Optimized solution for sorting.cpp, issue #35

### PR DESCRIPTION
**Pull request by digvijay2406**
I have used inbuilt function sort to reduce the time complexity and provide optimized solution for issue #35.

### CODE REVIEW

**Comment by Illuminati9** [comment]
Hey @digvijay2406 ,
Change the filename and remove the .exe file when making a PR.

**Comment by PavanaSakethaRam** [comment]
@digvijay2406 Can you add Screenshots for Reference

**Comment by Illuminati9** [comment]
Hey @digvijay2406 , Can you give do the problem by using another approach like using another sorting algorithm without using **inbuilt function**. And explain about the time complexity of the code after changing it.

**Comment by PavanaSakethaRam** [comment]
@digvijay2406 Since its been 14 hrs after we have requested for some changes, so we are closing the PR.

**Pull request closed without merging**
