### PR TITLE
Added Solution to Question_5 from issue #28

### PR DESCRIPTION
**Pull request by ashwinisingh17**
Hey @PavanaSakethaRam @Illuminati9 @shishiro26 , I have successfully provided the solution to the Question_5 from issue #28.

Please review this.

### CODE REVIEW

**Comment by Illuminati9** [comment]
Hey @ashwinisiningh , remove all the .exe files

**Review by shishiro26 — CHANGES_REQUESTED** [review]
Please create proper folder structure and remove all the .exe files @ashwinisiningh . Solve it asap and update it

**Review by Illuminati9 — APPROVED** [review]
LGTM

**Comment by PavanaSakethaRam** [comment]
@ashwinisiningh Can U remove all the changes u have made in any file other than your solution file. For Ex: The files in the SS attached.
image

**Review by PavanaSakethaRam — CHANGES_REQUESTED** [review]
Remove .exe files, changes made in the `Question_5.md` file and also change the solution from the file `Palindrome.cpp` to `Solution/Question_5.cpp` file and remove `solutions` file

**Review by Kota-Karthik — APPROVED** [review]

**Pull request closed without merging**
