### PR TITLE
Solved Question_3 #27

### PR DESCRIPTION
**Pull request by shibo911**
Hi,

I solved the Question_3 #27 as i was assigned.
I included all the constraints and run with all the examples. They all worked well. 

Thank you.
Screenshot 2023-10-19 151525

### CODE REVIEW

**Comment by PavanaSakethaRam** [comment]
@shibo911 Can you provide a better description along with any Screenshots(if needed)

**Comment by shibo911** [comment]
> @shibo911 Can you provide a better description along with any Screenshots(if needed)

I have edited my previous comment.

**Review by PavanaSakethaRam — COMMENTED** [review]
@shibo911 The solution you have provided passes only some of the test cases, so try changing the logic and optimize the code.

**Comment by shibo911** [comment]
> @shibo911 The solution you have provided passes only some of the test cases, so try changing the logic and optimize the code.

@PavanaSakethaRam  may I know the failed test cases, that will greatly help me in optimizing my code. thank you.

**Comment by PavanaSakethaRam** [comment]
@shibo911 That can't be done since those test cases are like the Hidden test cases in any contests like CodeChef or CodeForces. So try solving with any other logic.

**Comment by shibo911** [comment]
> @shibo911 That can't be done since those test cases are like the Hidden test cases in any contests like CodeChef or CodeForces. So try solving with any other logic.

@PavanaSakethaRam Actually both CodeChef and Codeforces can show test cases. CodeChef charges a price whereas codeforces shows all the test cases whether right or wrong for free. 

codeforces example:
Screenshot 2023-10-20 150631
Screenshot 2023-10-20 150617

**Comment by PavanaSakethaRam** [comment]
> > @shibo911 That can't be done since those test cases are like the Hidden test cases in any contests like CodeChef or CodeForces. So try solving with any other logic.
> 
> @PavanaSakethaRam Actually both CodeChef and Codeforces can show test cases. CodeChef charges a price whereas codeforces shows all the test cases whether right or wrong for free.
> 
> codeforces example: Screenshot 2023-10-20 150631 Screenshot 2023-10-20 150617

@shibo911 I think the code in the image in not the same code you have committed in the PR.

**Comment by shibo911** [comment]
> > > @shibo911 That can't be done since those test cases are like the Hidden test cases in any contests like CodeChef or CodeForces. So try solving with any other logic.
> > 
> > 
> > @PavanaSakethaRam Actually both CodeChef and Codeforces can show test cases. CodeChef charges a price whereas codeforces shows all the test cases whether right or wrong for free.
> > codeforces example: Screenshot 2023-10-20 150631 Screenshot 2023-10-20 150617
> 
> @shibo911 I think the code in the image in not the same code you have committed in the PR.

@PavanaSakethaRam My point is that both CodeChef and Codeforces can show test cases because you told that codechef and codeforces have hidden test cases (which is not).  The question that is mentioned in the screenshot is a sample question and it is obviously not the issue I have to solve. All I want to know is that where my program is failing, because it works perfectly fine with the sample input that was provided.

**Review by Kota-Karthik — APPROVED** [review]

**Comment by PavanaSakethaRam** [comment]
@shibo911 but in a good ICPC there will be some hidden test cases which will not be given

**Review by shishiro26 — APPROVED** [review]

**Review by akhilender-bongirwar — APPROVED** [review]

**Review by Illuminati9 — APPROVED** [review]
LGTM

**Pull request merged**
