### PR TITLE
Solved issue #29 Question_4 from Problems/Solution/Question4.md

### PR DESCRIPTION
**Pull request by Karanagarwal12**
Hey @PavanaSakethaRam ,
I have solved the issue #29 , check this out and please do merge my PR.
Made a folder with my roll number in the students folder and inside that in the solution folder I have given the solution for the mentioned problem and in the Alternate_Approach folder I have given another approach for the given problem.

### CODE REVIEW

**Comment by Illuminati9** [comment]
Hey @Karanagarwal12 ,
Can you provide me some screenshots for reference.

**Comment by Karanagarwal12** [comment]
@Illuminati9 ,
Which screenshots actually ?
The screenshot of the output ??
image

**Comment by PavanaSakethaRam** [comment]
@Karanagarwal12 I guess the Issue you have been assigned to have specified that you have to give ***SOLUTION*** to Question_4 but as I see you have also given an **Alternate Approach** for the same which is not required. So can you remove the Alternate Approach and then commit it so this PR can be merged.

**Comment by Karanagarwal12** [comment]
@PavanaSakethaRam,
Done. I removed the alternate approach file.

**Review by PavanaSakethaRam — CHANGES_REQUESTED** [review]
Remove the .exe files and also the .vscode folder

**Comment by Karanagarwal12** [comment]
@PavanaSakethaRam ,
Done. Removed all the unnecessary files.

**Review by Illuminati9 — APPROVED** [review]

**Review by shishiro26 — APPROVED** [review]

**Review by PavanaSakethaRam — APPROVED** [review]
@Karanagarwal12 LGTM 🚀

**Review by akhilender-bongirwar — APPROVED** [review]

**Pull request merged**
