### PR TITLE
Solved the Question_1 #26

### PR DESCRIPTION
**Pull request by 0PrashantYadav0**
Hi,

I solve the Question_1 i.e. issue #26 as i was assigned. I worked on all the constraints and run multiple test.

Thank you.
example_1
example_2
example_3

### CODE REVIEW

**Comment by Illuminati9** [comment]
Hey @0PrashantYadav0  ,
Can you provide me some screenshots for reference.

**Comment by 0PrashantYadav0** [comment]
Hi @Illuminati9 @PavanaSakethaRam ,

Done as per mentioned. Please review it.

**Review by PavanaSakethaRam — CHANGES_REQUESTED** [review]
@0PrashantYadav0 The Solution LGTM 👏 , but remove the changes made in the `readme.md` file to get your PR merged.

**Review by akhilender-bongirwar — CHANGES_REQUESTED** [review]
@0PrashantYadav0 , the solution you provided LGTM 👏 . But why did you make changes in the readme file ?

**Comment by 0PrashantYadav0** [comment]
hi @PavanaSakethaRam @akhilender-bongirwar 

I make changes as per requirement.
Please review it and merge my request

**Review by PavanaSakethaRam — APPROVED** [review]
@0PrashantYadav0 LGTM 🚀, Your PR will be merged once all the review checks have been done.

**Review by akhilender-bongirwar — APPROVED** [review]
Good work @0PrashantYadav0.

**Review by shishiro26 — APPROVED** [review]

**Comment by 0PrashantYadav0** [comment]
Hii @Illuminati9 please review so that it will get merge with main branch.

**Review by Illuminati9 — APPROVED** [review]

**Comment by PavanaSakethaRam** [comment]
@0PrashantYadav0 Congratulations on getting your first PR Merged 👏 Keep Going!!

**Pull request merged**
