### PR TITLE
Provided alternate approach for TOH.cpp issue #22

### PR DESCRIPTION
**Pull request by Karanagarwal12**
@PavanaSakethaRam @shishiro26 @akhilender-bongirwar ,
Solved issue #22 , I have made the alternate approach for the Tower of hanoi problem. Do check it out!!

### CODE REVIEW

**Review by Kota-Karthik — APPROVED** [review]

**Review by PavanaSakethaRam — APPROVED** [review]
LGTM 👏

**Review by Kota-Karthik — APPROVED** [review]

**Review by Kota-Karthik — APPROVED** [review]

**Review by shishiro26 — APPROVED** [review]
LGTM

**Review by akhilender-bongirwar — APPROVED** [review]
LGTM 👏

**Review by Illuminati9 — APPROVED** [review]
LGTM

**Pull request merged**
