### PR TITLE
added alternate solution for longset_subarray

### PR DESCRIPTION
**Pull request by Priyanshu-2005**
solved the problem using better solution 

issue no #36

### CODE REVIEW

**Comment by Priyanshu-2005** [comment]
logic:
traverse through the array and store prefix sum in map as key and position of iteration element as value 
count the length till when sum becomes equal to required sum


if sum-k is availaible in the map
then count the length of array from the current position of iteration to key to the element which has value has key equal to the sum-k





explanation of code 

firstly input size and elements of array
then input the sum for which we want the longest subarray

define a function longest subarray ,pass array ,array length and sum to the function
inside the function intialize the data structure map
initialize a variable sum and rem to keep track of sum,maxlen
traverse through the entire array using the loop and increment in each iteration by element of arrays also initialize each <key ,value>pair in map
key=sum
value =i
 
when the value of variable sum becomes equal to k then  if the variable maxlen is smaller then modify the value of maxlen to the length of the array traversed


then initialize the variable rem in which we store the value of variable sum-sum required(k)

if rem is already there in map then initialize a varilble l to store the length of the subarray required 
then compare l to maxlen if maxlen is smaller then modify the variable maxlen to length of subarray l

then return maxlen so that we get output as maxlen

**Review by Illuminati9 — CHANGES_REQUESTED** [review]
Hey @Priyanshu-2005 , remove all the .vscode files.

**Review by PavanaSakethaRam — CHANGES_REQUESTED** [review]
@Priyanshu-2005 The logic is good but remove the .vscode files to get your PR merged.

**Comment by Priyanshu-2005** [comment]
@Illuminati9  @PavanaSakethaRam changes made (vscode files removed)

**Review by Kota-Karthik — APPROVED** [review]

**Review by shishiro26 — APPROVED** [review]
LGTM 👏

**Review by akhilender-bongirwar — APPROVED** [review]
@Priyanshu-2005 LGTM 👏

**Pull request merged**
