### PR TITLE
alternate solution for palindrome  #24 issue 

### PR DESCRIPTION
**Pull request by saiganeshposhith**
optimize solution for palindrome  ,sir please review it   (lci2023032)

### CODE REVIEW

**Comment by Illuminati9** [comment]
Hey @saiganeshposhith , 
mention the issue in which you have been assigned and explain about the code and add some screenshots regarding your PR.

**Review by akhilender-bongirwar — CHANGES_REQUESTED** [review]
@saiganeshposhith , remove the .exe file.

**Review by PavanaSakethaRam — APPROVED** [review]
@saiganeshposhith LGTM 👏 But remove the .exe file to get your PR merged.

**Comment by saiganeshposhith** [comment]
sir i am unable to delete exe file i am creating new pr

**Review by Kota-Karthik — APPROVED** [review]

**Review by akhilender-bongirwar — APPROVED** [review]

**Review by shishiro26 — APPROVED** [review]

**Review by Illuminati9 — APPROVED** [review]
LGTM 👏

**Pull request merged**
