### PR TITLE
alternate solution of palindrome #24 issue

### PR DESCRIPTION
**Pull request by saiganeshposhith**
issue #24

### CODE REVIEW

**Comment by saiganeshposhith** [comment]
hi respected sir @PavanaSakethaRam  ,please review it(alternate solution for palindrome)

**Review by akhilender-bongirwar — CHANGES_REQUESTED** [review]
@saiganeshposhith, create a seprate folder for Alternate_approach inside the LCI2022032  then add palindrome.cpp.

**Comment by shishiro26** [comment]
@saiganeshposhith, it has been more than 12 hours. We will close this pull request, and the issue will be assigned to someone else due to the lack of response.

**Comment by Prudhvi-232** [comment]
@PavanaSakethaRam i want to work on this

**Pull request closed without merging**
